- README.md
Great project! I had a lot of fun making this.
I added my AutoLazy addin to the readme file.
> Added AutoLazy to the addins list

- FodyIsolated/DelegateBuilders/DelegateBuilder.cs
Based on the issues noted here:
https://github.com/Fody/Costura/issues/115
> Improved warning message when weaver cannot be loaded

- README.md
I have created a custom adding for Fody, if you would like add it to the addins' list, I would much appreciate that.
> Added new addin - Seal

- README.md
With.Fody addin extends immutable C# classes with `With()` methods to return a copy of an object with one property modified.
> Add a link to With plugin

- Fody.Tests/NuGetPackageRootTest.WithNuGetPackageRoot.approved.txt
- Fody/AddinFinder/AddinSearchDirectories.cs
Fixes #331 
The Nuget weaver search, ScanNuGetPackageRoot, now pulls all packages and DLLs regardless of casing, while still matching the convention.
Packages are matched as either case:
* `<PackageName>.Fody`
* `<packagename>.fody`
DLLs are matched as either case:
* `<packagename>.fody.dll`
* `<PackageName>.Fody.dll`
Some of the filter is done in code instead of the file system pattern request, but it should still generally filter well up front.
The `WithNugetPackageRoot` test was updated. The fake weaver folder for weaver 2 was changed to lower case, but the DLLs inside are upper case. A new approval test capture was required, as the changed case value was updated.
This addresses the specific issue raised with nuget on mac using Mono to execute a build, and should make the process a …
> Changed Nuget weaver package search to be case insensitive

- README.md
Adjusted description of StaticProxy.
> Update README - description of StaticProxy

- README.md
I do not plan on further supporting the Fody integration of my SemVer-extension (https://github.com/dittodhole/dotnet-SemVer.Stamp).
> removed SemVer module

- Fody/Processor.cs
- Fody/WeavingTask.cs
- FodyCommon/IInnerWeaver.cs
- FodyIsolated.Tests/WeaverInitialiserTests.cs
- FodyIsolated/DelegateBuilders/DelegateBuilder.cs
- FodyIsolated/InnerWeaver.cs
- FodyIsolated/WeaverDelegate.cs
- FodyIsolated/WeaverInitialiser.cs
- NuGet/Fody.targets
- SampleWeaver.Fody/ModuleWeaver.cs
> Documentation file path

- Directory.Build.props
- Fody/AddinFinder/AddinSearchDirectories.cs
> Fix package finder for linux. (Fixes #477)

- Integration/Weavers/Weavers.csproj
demonstrate https://github.com/Fody/Fody/issues/491
contains only the last commit of https://github.com/Fody/Fody/pull/492
> [Failing test] for #491

- README.md
> Add InlineIL to addin list

- Fody/AddinFinder/AddinSearchDirectories.cs
- Fody/AddinFinder/DirectoryEx.cs
Fixes failed builds on Linux. Fixes https://github.com/Fody/Costura/issues/268
**Confirmed working:**
https://github.com/Xathz/Spell-Check/commit/4e8a88a504dda54b44ba447c1ec07fe05b82d487
https://api.travis-ci.org/v3/job/363662503/log.txt
**Thanks for the idea:** https://github.com/Fody/Costura/issues/268#issuecomment-379514579
> Changed Nuget packages directory to be case insensitive

- DummyAssembly/Class1.cs
- FodyHelpers/Testing/WeaverTestHelper.cs
- Tests/FodyHelpers/WeaverTestHelperTests.cs
> Fix Issue#532

- README.md
Created a new addin for Fody, added this one to the readme addins list
> Add LoggerIsEnabled to the readme addins list

- Fody/Fody.targets
Just a minor clean-up of target inputs that [I noticed](https://github.com/Fody/Fody/issues/582#issuecomment-433638624) could be made.
> Target inputs cleanup

- FodyHelpers/BaseModuleWeaver.cs
Add some xml doc to describe the new behavior of the @(ReferenceCopyLocalPaths)
> Extend documentation

- Fody.sln
- FodyPackaging/build/FodyPackaging.props
- FodyPackaging/build/FodyPackaging.targets
- SampleWeaver/SampleWeaver.csproj
Fix #596: Packaging now fails if no weavers are included in package
> Fix #596: Packaging now fails if no weavers are included in package

- Fody.sln
- Fody/Fody.targets
- README.md
Fix #601: remove VS2017 specific item
This was just a "nice to have" feature, users can easily add this by their own.
> Fix #601: remove VS2017 specific item

- Fody/ConfigFileFinder.cs
- Fody/Resources/FodyWeavers_SchemaTemplate.xml
- Tests/Fody/ConfigFileFinderTests.cs
> Add an option to opt out of xsd generation

- Fody/Fody.targets
This adds FodyWeavers.xml to the list of files that will be checked to determine if the project is up-to-date in the new project system.
This is documented [here](https://github.com/dotnet/project-system/blob/master/docs/repo/up-to-date-check.md).
> Add up-to-date check for FodyWeavers.xml

- Fody/Fody.targets
Fixes #663 
All credits go to @ltrzesniewski
> Prevent multiple executions of Fody against reference assemblies

- FodyHelpers/Guard.cs
Added namespace to Guard class to prevent conflict.
> Add namespace on Guard

- Fody.sln.DotSettings
- Fody/Fody.targets
- Fody/Processor.cs
- Fody/WeavingTask.cs
- FodyCommon/WeaverEntry.cs
- FodyIsolated/InnerWeaver.cs
- FodyIsolated/PackageReferenceValidator.cs
- SampleWeaver.Fody/ModuleWeaver.cs
- Tests/Fody/WeavingTaskTests.cs
- Tests/FodyIsolated/ValidatePackageReferenceSettingsTests.cs
- Tests/Tests.csproj
#851: Verify correct settings of PrivateAssets
> Validate package reference settings

- FodyIsolated/InnerWeaver.cs
> Fix Fody#895.

- FodyIsolated/InnerWeaver.cs
give more information when https://github.com/dotnet/runtime/issues/27533 is detected
> Catch value tuple

- vsts-integration.yml
Extend integration build to build using "dotnet build/test"
> Build dotnet

- FodyIsolated/AssemblyExtensions.cs
- FodyIsolated/InnerWeaver.cs
Add version and weaver name so we know we are using the right version of a weaver.
> Log weaver name and version

- Fody/Fody.targets
- Fody/Processor.cs
- Fody/UpdateReferenceCopyLocalTask.cs
- Fody/WeavingTask.cs
- FodyCommon/IInnerWeaver.cs
- FodyHelpers/BaseModuleWeaver.cs
- FodyHelpers/ReferenceCleaner.cs
- FodyHelpers/Testing/WeaverTestHelper.cs
- FodyIsolated/InnerWeaver.cs
- FodyIsolated/WeaverInitialiser.cs
- Integration/SampleTargetTests/PackagedWeaverTests.cs
- SampleWeaver.Fody/ModuleWeaver.cs
- vsts-integration.yml
Cleaned library references are not removed from the deps.json file
> Fix  #1090

- Directory.Build.props
- Fody/Fody.targets
> #1167 assembly has already been processed by fody

- Directory.Build.props
- Fody.sln
- Fody/Fody.nuspec
- FodyHelpers.Tests/FodyHelpers.Tests.csproj
- Tests/Tests.csproj
- package_readme.md
> Embed a simplified readme in the nuget package
