Fody/Fody

Fody/BuildLogger.cs
FodyIsolated/DelegateBuilders/PropertyDelegateBuilder.cs

A log prefix with the name of the weaver was already done at the warning and error logging level. I just extended this to the Info and Debug levels too.
Also fixes a delegate bug in the tests with Roslyn.

Logging prefixes at all levels

---

Fody/WeaverProjectFileFinder.cs

Create the search path in a portable way, since a path with '\' is not valid in Linux and Directory.Exists will always return False.

Fix weaver project search path in Linux

---

FodyIsolated.Tests/DelegateBuilders/PropertyDelegateBuilderTests.cs
FodyIsolated/DelegateBuilders/PropertyDelegateBuilder.cs

Hi there,
I'm working on an intermediate add-in to supply further (vaguely planned) add-ins with functionality, and decided the best way to do this would be by ModuleWeaver base class.
I've not completely proved the idea to myself yet, but this was the first hurdle: a slight bug in building the property-setting delegates, which meant that accessors for inherited properties weren't being compiled.
Thanks!

Fixed setting inherited props on weaver

---

NuGet/Fody.targets

There were two issues both relating to peverify:
1) PeVerify wasn't run at all because of how the target defined the inputs / outputs.
after fixing 1) in the first commit, I noticed another issue:
2) If peverify fails, it correctly fails the build.
But if I then run another incremental build, it just skips the project, because the output file already exists.
I fixed that by scheduling peverify earlier, before the exe/dll was copied from obj to bin.
That way, msbuild will rerun peverify and the build will fail again.

Fix #227 peverify not called

---

FodyIsolated.Tests/FakeModuleWeaver.cs
FodyIsolated/InnerWeaver.cs

I was working on updating my add-in for jasonwoods-7/Vandelay#2, and I found that when executing the Stamp.Fody add-in, it is throwing the following exception:
```
MSBUILD : error : Fody: An unhandled exception occurred:\r [R:\home\jwoods\src\git\AssertMessage\Fody\Fody.csproj]
MSBUILD : error : Exception:\r [R:\home\jwoods\src\git\AssertMessage\Fody\Fody.csproj]
MSBUILD : error : The process cannot access the file 'R:\home\jwoods\src\git\AssertMessage\Fody\obj\Debug\AssertMessage.Fody.dll.tmp' because it is being used by another process.\r [R:\home\jwoods\src\git\AssertMessage\Fody\Fody.csproj]
MSBUILD : error : StackTrace:\r [R:\home\jwoods\src\git\AssertMessage\Fody\Fody.csproj]
MSBUILD : error :    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)\r …
```

fix for when a weaver has an AfterWeaving method.

---

FodyIsolated/ModuleReader.cs
FodyIsolated/ModuleWriter.cs
FodyIsolated/SymbolsFinder.cs

Fixes #314, which I needed to test #312

Allow Fody to run even when no debug symbols are present

---

Fody/Processor.cs
Fody/WeavingTask.cs
FodyCommon/IInnerWeaver.cs
FodyIsolated/InnerWeaver.cs
FodyIsolated/SymbolsFinder.cs
NuGet/Fody.targets

Passing the `DebugSymbols` flag from MSBuild to fix issue #333

Added DebugSymbols build parameter to Fody

---

Fody/AddinFinder/AddinSearchDirectories.cs

.. to be able to deduce the path the code executes on from the logs.
Downside: As there's no "IfDebugEnabled" on the `ILogger` interface and no `Func<string>` overload it is slightly expensive to log the whole list of PackageDefinitions.

Made logging more verbose for AddInFinder.FindAddinDirectories

---

README.md

Was:
-Supported Runtimes
-Edit & Continue not supported
-- Reasons (=> belongs to "Supported Runtimes")

Fixed broken sequence Readme.MD chapters

---

README.md

We implemented an addin for Fody, which works like the MethodBoundaryAspect of PostSharp (saving a method tag and access method information).

Added MethodBoundaryAspect to addin list.

---

Fody/Fody.targets

Looks like NCrunch support was broken by the `netstandard`/`netclassic` directory split. This fixes the issue by including the correct directory instead of the (now basically empty) root one.

Fix NCrunch support

---

FodyIsolated/AssemblyResolver.cs
Tests/FodyCommon/NullLogger.cs
Tests/FodyIsolated/AssemblyResolverTests.cs

AssemblyResolver assumes the assembly name is always equal to the file name. This leads to issues such as  https://github.com/Fody/PropertyChanged/pull/181
This PR causes the resolver to attempt to read the assembly identity from the given file before falling back to this assumption.

Try to get the real assembly name in AssemblyResolver

---

README.md

This page was deleted from the wiki and Usage is already explained in this README.

Removed dead link to wiki from README

---

README.md

This changes the description of InlineIL.
I removed the reference to `ILGenerator` since the InlineIL API evolved into something completely different a while ago, and no longer tries to mimic `ILGenerator`. The previous description seemed outdated.

Update InlineIL description

---

README.md

Realm is not an addin, I suppose it's a project that uses Fody.

README.md: move an element out of addins list

---

FodyIsolated/InnerWeaver.cs
Tests/FodyIsolated/AssemblyVersionTests.cs

As discussed [here](https://github.com/Fody/Fody/issues/556), I've implemented a fix and added a unit test to ensure there are no breaking changes.
The fix should not affect anyone who had things working for them so far. It only addresses rare and specific scenario where assembly version could not be retrieved from file, because there is no file (i.e. the assembly is embedded in another or otherwise dynamically resolved).
Feel free to comment on the implementation!

Fetching the version info from AssemblyFileVersionAttribute when Assembly.Location is not available

---

Fody/Fody.targets
FodyPackaging/Weaver.Props.Template

This makes the addins play nicely with NCrunch by default.
I also inverted netclassicweaver/netstandardweaver because I noticed my "fulll .NET" MSBuild was using the netstandardweaver version.
I renamed  `RuntimeToken` to `WeaverRuntimeToken` to make it more specific to Fody, just in case.
Finally, I couldn't reproduce any issues by eliminating the `FilesToAdd` intermediate item, so I removed the indirection.

Add NCrunch support to weavers by default

---

Fody/Fody.targets

- `FodySignAssembly` has been removed and replaced by `SignAssembly`. This change is due to ltrzesniewski/InlineIL.Fody#4.
- Replaced the `Choose` block with conditioned properties. This makes the file much simpler.
- Added a condition on `FodyAssembly` to make #569 easier to merge (will still cause a conflict, unfortunately).
- Made indentation consistent across the file, and reordered it to match MSBuild evaluation order: properties, then items then tasks.
If you prefer me not to mess with whitespace or tag order, I can revert this but keep the first two points.

Simplify Fody.targets

---

Fody.sln
FodyHelpers/ReferenceCleaner.cs
FodyIsolated/InnerWeaver.cs
Integration/WithNugetWeavers/WithNugetWeavers.csproj
SampleWeaver.Fody/ModuleWeaver.cs
Tests/FodyHelpers/WeaverTestHelperTests.Run.approved.txt
Tests/FodyHelpers/WeaverTestHelperTests.WeaverUsingSymbols.approved.txt
Tests/FodyHelpers/WeaverTestHelperTests.WithCustomAssemblyName.approved.txt

Thanks to #568 we can now easily prevent the weaver libraries from being copied to the output directory when the reference to the weaver is cleaned. This PR does just that.
Note that the "integration test" for this change is in `WithNugetWeavers.csproj` - I couldn't think of a better way to test this.

Prevent weaver lib from being copied to build output when not referenced

---

Directory.Build.props

Fix #580: use microsoft source link to enrich pdbs with github information
replaces #581

Fix #580: use source link to enrich pdbs with github information

---

FodyPackaging/build/FodyPackaging.props

FodyPackaging misbehaves when `$(SolutionDir)` is not set (for instance when building a single project), because an empty path is passed to `[MSBuild]::GetDirectoryNameOfFileAbove`, which throws the following error:
> error MSB4184: The expression "[MSBuild]::GetDirectoryNameOfFileAbove('', .git\index)" cannot be evaluated. The path is not of a legal form. 
This PR fixes that by using `$(MSBuildProjectDirectory)` as a starting point instead.
I also noticed that `$(LocalGitRootFolder)` should have a trailing slash, so this change ensures that as well.

Do not require a solution for FodyPackaging to work

---

README.md

[ReactiveUI.Fody](https://www.nuget.org/packages/ReactiveUI.Fody/) now lives in ReactiveUI main repo.

Change ReactiveUI.Fody add-in link

---

readme.md

I think these two links are better link to send the companies to. We'll be shipping a new contribution flow soon and that wiki section will be deprecated.

update open collective sponsor link

---

Fody/ConfigFileFinder.cs
Fody/Fody.targets
Fody/Processor.cs
Fody/Verify/Verifier.cs
Fody/WeavingTask.cs
Tests/Fody/ConfigFileFinderTests.cs
Tests/Fody/ProjectWeaversFinderTests.cs

This is an addition to #615. It adds a `FodyGenerateXsd` MSBuild property which you can set to `false` to opt out of XSD generation. You can apply this to a whole solution by setting it in the `Directory.Build.props` file.
This property sets a default: you can still write `GenerateXsd="true"` in `FodyWeavers.xml` to override this setting.

Add support for FodyGenerateXsd MSBuild property

---

FodyPackaging/build/FodyPackaging.props

In ReactiveUI.Fody we are using the new recommended way of using **PackageLicenseExpression** (or **PackageLicenseFile** but we opted into using the Expression).
[FodyPackaging.props](https://github.com/Fody/Fody/blob/e924e1f361ab36fd37b5dff77561965285f05eae/FodyPackaging/build/FodyPackaging.props#L43) is setting a _PackageLicenseUrl_ if none is found and this is producing the following error:
```
error NU5035: The PackageLicenseUrl is being deprecated and cannot be used in conjunction with the PackageLicenseFile or PackageLicenseExpression.
```
1. For the case of a Fody based package, unless there is a PackageLicenseExpression, PackageLicenseUrl or PackageLicenseFile set, set the PackageLicenseExpression to MIT
2. In the case of externally hosted URL add additional checks for the …

fix: Made the Fody.Packaging compatible with the new Nuget license tags in csproj

---

Fody/Fody.targets

Minor cleanup: This causes the cache file to be deleted when the Clean target is called.

Register the references cache file

---

Fody/Fody.targets

@SimonCropp Sorry but I wasn't clear in #651 and I think you misunderstood what the change does.
That change ensured that MSBuild would be called if FodyWeavers.xml is changed, but this doesn't mean that the CoreCompile target would run, which means that FodyTarget could be called on an already weaved assembly.
This PR fixes that by adding FodyWeavers.xml to the list of dependencies of CoreCompile.
(I thought about doing what you did in #652 and including this change but only after you merged #651)

Make the CoreCompile target depend on FodyWeavers.xml

---

FodyPackaging/build/FodyPackaging.props

This is a breaking change to FodyPackaging.
Some history: FodyPackaging was originally created to only build packages from within the Fody Org. As such many things were hard coded (or specified with a rigid convention) eg license, icon, output dir, project url. FodyPackaging was then made more flexible so it could target projects outside the Fody Org. This was a good change, but had some side effects
* to achieve this significant complexity had to be added to make the above conventions  overridable or tweaked. 
* pulled in the assumption/convention that all fody addins are hosted on github.
* complexity and fragility around determining the output path
Moving forward i believe this will be difficult to document and to maintain
This PR remove those conventions that are complex or overly …

Simplify FodyPackaging

---

Fody/Fody.targets

Allows ProjectWeaverXml to be set externally
Only set ProjectWeaverXml when it hasn't been set already
Allows doing something like:
```
<ProjectWeaverXml Condition="'$(Configuration)' == 'Release'">$(ProjectDir)FodyWeavers.xml</ProjectWeaverXml>
<ProjectWeaverXml Condition="'$(Configuration)' == 'Debug'">$(ProjectDir)FodyWeavers.xml</ProjectWeaverXml>
```

Allow ProjectWeaverXml to be set externally

---

Fody/ConfigFileFinder/ConfigFileFinder.cs
Fody/Processor.cs
Tests/Fody/ConfigFileFinderTests.cs
Tests/Tests.csproj

Right now, having a solution level config file without a project level one is supported. But `EnsureSchemaIsUpToDate` doesn't care about that and will therefore throw an exception if it doesn't find a config file in the project directory (it only checks for project level, even though earlier in the callstack if neither project or solution level one is found a project level one is generated automatically).
This PR avoids throwing exception during `EnsureSchemaIsUpToDate` when a solution config is specified.
During `EnsureSchemaIsUpToDate`, a `string solutionDirectory` argument has been added, so that both project and solution file can be checked. Will only try to ensure schema is up to date if the respective file exists.

Solution-wide config support for `EnsureSchemaIsUpToDate`

---

FodyIsolated/InnerWeaver.cs

Assembly Resolve event was only unregistered when an exception was thrown. During normal processing the event registration remains and leads to a memory leak. The loaded assemblies could no longer be freed and kept in memory as long as the msbuild process was running. In our project this leak lead to build aborts because of OutOfMemoryException.  This pull request addresses the issue and fixes it by deregistering the event in the normal flow of execution.
For more detail see: #752

EventHandler Memoryleak in InnerWeaver

---

Directory.Build.props
FodyIsolated/InnerWeaver.cs

qualify ProcessedByFody namespace with "_Fody"

---

FodyIsolated/InnerWeaver.cs

instead prefix the type with the assembly name

dont put ProcessedByFody in namespace

---

Fody/BuildLogger.cs
Fody/DomainAssemblyResolver.cs
Fody/ExtractConstants.cs
Fody/Processor.cs
Fody/Verify/VerifyTask.cs
Fody/WeavingTask.cs
FodyCommon/IInnerWeaver.cs
FodyCommon/ILogger.cs
FodyCommon/WeaverEntry.cs
FodyHelpers/BaseModuleWeaver.cs
FodyHelpers/Testing/Ildasm.cs
FodyHelpers/Testing/SymbolReaderProvider.cs
FodyIsolated/AssemblyResolverHelper.cs
FodyIsolated/InnerWeaver.cs
FodyIsolated/TypeFinder.cs
Tests/Fody/MockBuildLogger.cs
Tests/FodyIsolated/AssemblyResolverTests.cs

I noticed a few nullable reference type annotations were off when doing my previous changes, so I quickly reviewed the annotations in the Fody projects. It doesn't fix everything, since it would require large changes to the codebase (there are still many properties with a `= null!` initializer), but it's a step in the right direction.

Adjust nullable reference types annotations

---

DummyExeAssembly/DummyExeAssembly.csproj
DummyExeAssembly/Program.cs
Fody.sln
FodyHelpers.Tests/FodyHelpers.Tests.csproj
FodyHelpers.Tests/IldasmTests.cs
FodyHelpers.Tests/WeaverTestHelperTests.WithCustomExeAssemblyName.verified.txt
FodyHelpers.Tests/WeaverTestHelperTests.cs
FodyHelpers/Testing/WeaverTestHelper.cs
Tests/FodyIsolated/AssemblyResolverTests.cs
Tests/Tests.csproj

Before this pull request, when supplying a custom assembly name, the target file would be renamed with `.dll` when weaving an `.exe` file. This was confusing.

Keep the original file extension in WeaverTestHelper.ExecuteTestRun

---

Fody/Fody.targets

When `ReferenceCopyLocalPaths` is updated by Fody, the information of _which_ `ReferenceCopyLocalPaths` were removed is lost.
Why is this important to have this information? Because when using Costura and the `Publish` MSBuild target, the dlls that were removed from the build output directory end up in the publish output directory anyway, even though they are already embedded in the executable. With this new information available, it becomes possible to fix the publishing task like this:
```xml
<Target Name="RemoveAlreadyEmbeddedFilesFromPublish" AfterTargets="ComputeResolvedFilesToPublishList">
<ItemGroup>
<ResolvedFileToPublish Remove="@(FodyRemovedReferenceCopyLocalPaths)" />
</ItemGroup>
</Target>
```
I plan to submit this fix to Costura.Fody but I need the list of removed …

Add new FodyRemovedReferenceCopyLocalPaths MSBuild item

---

Fody/Fody.targets
Fody/Processor.cs
Fody/WeavingTask.cs
FodyCommon/IInnerWeaver.cs
FodyIsolated/InnerWeaver.cs
FodyIsolated/StrongNameKeyFinder.cs

Explicitly handle the `<DelaySign>` property.

Fix #985: Build fails when using dotnet cli and strong assembly

---

Fody/BuildLogger.cs
Fody/Processor.cs
FodyHelpers.Tests/WeaverTestHelperTests.Run.verified.txt
FodyHelpers.Tests/WeaverTestHelperTests.WeaverUsingSymbols.verified.txt
FodyHelpers.Tests/WeaverTestHelperTests.WithCustomAssemblyName.verified.txt
FodyHelpers.Tests/WeaverTestHelperTests.WithCustomExeAssemblyName.verified.txt
FodyHelpers/ReferenceCleaner.cs
FodyIsolated/AssemblyReferenceFinder.cs
FodyIsolated/InnerWeaver.cs
FodyIsolated/ModuleWriter.cs
FodyIsolated/WeaverInitialiser.cs

This is just a small cleanup of log messages as I noticed some inconsistencies in their indentation. I hope that's OK for you @SimonCropp.
See also https://github.com/KirillOsenkov/MSBuildStructuredLog/pull/506 - I don't think MSBuild tasks are supposed to log messages ending with a newline.
<details>
<summary>Difference in detailed logging mode</summary>
Before:
```
Fody: Fody (version 6.5.1.0 @ file:///C:/Users/lucas/Documents/Dev/Fody/packages/fody/6.5.1/netclassictask/Fody.dll) Executing
Fody: SolutionDirectory path is 'C:\Users\lucas\Documents\Dev\Fody\Integration\'
Fody: ProjectDirectory: 'C:\Users\lucas\Documents\Dev\Fody\Integration\WithEmbeddedPdb'.
Fody: ProjectFile: 'C:\Users\lucas\Documents\Dev\Fody\Integration\WithEmbeddedPdb\WithEmbeddedPdb.csproj'.
Fody: AssemblyFile: …
```

Cleanup indentation of log messages

---

vsts-integration.yml

Just simplify the existing azure pipeline definition by using a build matrix and using VS2022 as the primary build.

Update cross platform integration tests

---

Fody/BuildLogger.cs
Fody/Fody.targets
Fody/WeavingTask.cs
Tests/Fody/BuildLoggerTests.cs

I figured maybe Fody should take `$(TreatWarningsAsErrors)` into account, and emit errors instead of warnings when this property is set to true.
This PR adds a `FodyTreatWarningsAsErrors` property which is set to `$(TreatWarningsAsErrors)` by default, but can be overridden if needed.
This is a suggestion, tell me what you think. **This could be a breaking change to existing users.**
Note that the same outcome can be achieved without this PR by setting `$(MSBuildTreatWarningsAsErrors)` to true - in that case *any* warning emitted during the build will become an error, not just Fody warnings.
*(sorry for all the edits, I must have pressed a shortcut and the PR got submitted before I finished writing the summary)*

Take `$(TreatWarningsAsErrors)` into account

---

Fody/AssemblyPathSet.cs
Fody/Processor.cs
FodyIsolated/AssemblyLoader.cs
Tests/Fody/AssemblyPathSetTests.cs

Currently, Fody creates an assembly load context per solution directory. A problem with that approach is that if two projects in the same solution try to load two different versions of the same weaver on a single build node, the second load will fail.
This PR changes this logic to create assembly load contexts based on the *set of weaver assembly paths* which will be used in a given project. Therefore, two projects which use two different versions of the same weaver will get two different load contexts since the weaver path won't be the same (and even if it were the same path, the `WeaversHistory` class already takes care of this case).
Note that I may be missing some context here (I don't know why the load contexts were cached by solution path or why they were cached in the first place). …

Base load contexts on weaver paths

---

FodyHelpers/Testing/WeaverTestHelper.cs

Add folder name to test weaver

---

FodyIsolated/ModuleWriter.cs
FodyIsolated/StrongNameKeyFinder.cs

(I tried becoming one but my card was declined)
This PR uses an alternative way to pass to Cecil the strong-name key pair, without needing to create legacy `StrongNameKeyPair` objects. This will reduce Fody's reliance on its fork of Mono.Cecil, and unless there are other reasons to use it, I can replace it with the upstream NuGet package in this or a subsequent PR.
Instead of setting a `StrongNameKeyPair` to `WriterParameters.StrongNameKeyPair`, we pass the key file's content directly to the `StrongNameKeyBlob` property. Cecil will read it in a cross-platform way.
Fody has been using the `StrongNameKeyPair.PublicKey` property to set the assembly name's public key, and determine if the file actually points to a private key. This PR stops changing the assembly name because I discovered that …

Avoid constructing `StrongNameKeyPair`.

---

FodyHelpers.Tests/FodyHelpers.Tests.csproj
FodyTasks/FodyTasks.csproj
Tests/Tests.csproj

I am.
If you are uncertain if the PR will be accepted, outline the proposal in an issue to confirm it is viable.
Even if the feature is a good idea and viable, it may not be accepted since the ongoing effort in maintaining the feature may outweigh the benefit it delivers.
Building `Fody.sln` with the .NET 10 SDK causes the following warnings-turned-errors:
```
8>error NU1903: Warning As Error: Package 'Microsoft.Build.Tasks.Core' 17.11.4 has a known high severity vulnerability, https://github.com/advisories/GHSA-h4j7-5rxr-p4wc
11>C:\Users\teo\code\Fody\FodyHelpers.Tests\FodyHelpers.Tests.csproj : error NU1510: Warning As Error: PackageReference Microsoft.CSharp will not be pruned. Consider removing this package from your dependencies, as it is likely unnecessary. …
```

Clean-up unnecessary dependencies.
